language: php

php:
  - 5.4

services: memcache

install:       chmod +x bin/travis-ci/install_dependencies && bin/travis-ci/install_dependencies
before_script: composer install --dev
script:         phpunit --coverage-text --verbose

notifications:
  email:
    - github@perbility.de